version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - poetry config virtualenvs.create false
      - poetry install --with docs

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
