[tool.poetry]
name = "gen_surv"
version = "0.1.0"
description = "A Python package for simulating survival data, inspired by the R package genSurv"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "gen_surv" }]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26"

[tool.poetry.dev-dependencies]
pytest = "^8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
