[tool.poetry]
name = "gen_surv"
version = "0.1.0"
description = "A Python package for simulating survival data, inspired by the R package genSurv"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "gen_surv" }]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26"
pandas = "^2.2.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[tool.semantic_release]
version_source = "tag"
version_variable = ["pyproject.toml:project.version"]
commit_version_number = true
changelog_file = "CHANGELOG.md"
upload_to_repository = false
branch = "main"
build_command = ""

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
