"""Compute the preregistered H1--H4 estimands from processed results.

    python scripts/analyze_hypotheses.py --processed results/processed

Writes ``hypotheses.parquet``, ``hypotheses.json`` and a LaTeX macro file. The
manuscript and tables should consume those artifacts rather than recomputing
hypothesis quantities ad hoc.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))

from survival_misspec.hypotheses import analyse_hypotheses  # noqa: E402

HEADER = (
    "% Generated by scripts/analyze_hypotheses.py from {source}.\n"
    "% Do not edit: re-run the script.\n"
)

HYPOTHESIS_WORDS = {
    "H1": "HOne",
    "H2": "HTwo",
    "H3": "HThree",
    "H4": "HFour",
}


def _write_macros(hypotheses: pd.DataFrame, path: Path, source: Path) -> None:
    """Write stable manuscript macros for the H1--H4 decision rows."""
    lines = [HEADER.format(source=source.as_posix()).rstrip()]
    for row in hypotheses.itertuples():
        stem = HYPOTHESIS_WORDS.get(str(row.hypothesis), str(row.hypothesis))
        decision = "supports" if row.supports_hypothesis else "does not support"
        lines.extend(
            [
                f"\\newcommand{{\\Hypothesis{stem}Estimate}}{{{row.estimate:.4f}}}",
                f"\\newcommand{{\\Hypothesis{stem}N}}{{{int(row.n)}}}",
                f"\\newcommand{{\\Hypothesis{stem}Decision}}{{{decision}}}",
            ]
        )
        if (
            hasattr(row, "estimate_se")
            and pd.notna(row.estimate_se)
            and pd.notna(row.estimate_ci_low)
            and pd.notna(row.estimate_ci_high)
        ):
            lines.extend(
                [
                    f"\\newcommand{{\\Hypothesis{stem}SE}}{{{row.estimate_se:.4f}}}",
                    f"\\newcommand{{\\Hypothesis{stem}CILow}}{{{row.estimate_ci_low:.4f}}}",
                    f"\\newcommand{{\\Hypothesis{stem}CIHigh}}{{{row.estimate_ci_high:.4f}}}",
                ]
            )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--processed", default=str(HERE.parent / "results" / "processed")
    )
    parser.add_argument(
        "--macros", default=str(HERE.parent / "paper" / "macros" / "hypotheses.tex")
    )
    arguments = parser.parse_args()

    processed = Path(arguments.processed)
    summary_path = processed / "summary.parquet"
    if not summary_path.exists():
        print(f"no summary at {summary_path}; run aggregate_results.py first")
        return 1

    hypotheses = analyse_hypotheses(pd.read_parquet(summary_path))
    parquet_path = processed / "hypotheses.parquet"
    json_path = processed / "hypotheses.json"
    macros_path = Path(arguments.macros)
    hypotheses.to_parquet(parquet_path, index=False)
    json_path.write_text(
        json.dumps(hypotheses.to_dict("records"), indent=2), encoding="utf-8"
    )
    _write_macros(hypotheses, macros_path, parquet_path)
    print(f"hypotheses     {len(hypotheses)} rows -> {parquet_path}")
    print(f"json           {json_path}")
    print(f"macros         {macros_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
