"""Generate every numerical table in the paper from saved result files.

    python scripts/make_tables.py --processed results/processed --config config

Writes LaTeX to ``paper/tables/``. **No numeric value is ever typed into the
manuscript by hand.** Each file carries a generated-by header, and
``tests/test_tables.py`` fails if a table in ``paper/tables/`` lacks one --
which is what stops a number being pasted in and then quietly diverging from
the results it came from.

Tables 1 and 2 describe the design and can be produced before any run. Tables
3 to 5 need results and are skipped with a message when they are absent, rather
than emitting an empty table that looks finished.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))

from survival_misspec.config import load_study  # noqa: E402

HEADER = (
    "% Generated by scripts/make_tables.py from {source}.\n"
    "% Do not edit: re-run the script. A hand-edited number here would no\n"
    "% longer correspond to any result and nothing would detect the drift.\n"
)


def _escape(text: str) -> str:
    for old, new in (("_", r"\_"), ("%", r"\%"), ("&", r"\&")):
        text = text.replace(old, new)
    return text


def _write(path: Path, body: str, source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER.format(source=source) + body, encoding="utf-8")
    print(f"  {path.name}")


def _pm(mean: float, mcse: float, digits: int = 4) -> str:
    """A value with its Monte Carlo error, never one without the other."""
    if pd.isna(mean):
        return "---"
    if pd.isna(mcse):
        return f"{mean:.{digits}f}"
    return f"{mean:.{digits}f} \\;({mcse:.{digits}f})"


def table_scenarios(study, out: Path) -> None:
    rows = []
    seen = set()
    for scenario in study.scenarios:
        if scenario.dgp in seen:
            continue
        seen.add(scenario.dgp)
        rows.append((scenario.dgp, scenario.misspecification))

    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Data-generating mechanisms, and what each does to a "
        r"proportional-hazards model.}",
        r"\label{tab:scenarios}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"Mechanism & Departure from proportional hazards \\",
        r"\midrule",
    ]
    for dgp, misspecification in sorted(rows):
        body.append(f"\\texttt{{{_escape(dgp)}}} & {_escape(misspecification)} \\\\")
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    _write(out / "table1_scenarios.tex", "\n".join(body), "config/simulation.yaml")


def table_estimators(study, out: Path) -> None:
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Estimators and the assumptions each makes.}",
        r"\label{tab:estimators}",
        r"\begin{tabular}{lp{9cm}}",
        r"\toprule",
        r"Estimator & Assumptions \\",
        r"\midrule",
    ]
    for estimator in study.estimators:
        body.append(
            f"\\texttt{{{_escape(estimator.estimator_id)}}} & "
            f"{_escape(estimator.assumptions)} \\\\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    _write(out / "table2_estimators.tex", "\n".join(body), "config/estimators.yaml")


def table_main_results(summary: pd.DataFrame, out: Path) -> None:
    """The primary loss beside the metrics that are supposed to stand in for it.

    Every entry carries its Monte Carlo error. Two values whose intervals
    overlap are not distinguishable at this replication count, and the table is
    laid out so a reader can see that rather than having to be told.
    """
    needed = ["dgp", "estimator_id", "mise_mean", "mise_mcse"]
    missing = [c for c in needed if c not in summary.columns]
    if missing:
        print(f"  table3: skipped, missing {missing}")
        return

    grouped = (
        summary.groupby(["dgp", "estimator_id"])
        .agg(
            mise=("mise_mean", "mean"),
            mise_mcse=("mise_mcse", "mean"),
            c_index=("c_index_harrell_mean", "mean"),
            c_index_mcse=("c_index_harrell_mcse", "mean"),
            ibs=("integrated_brier_score_mean", "mean"),
            ibs_mcse=("integrated_brier_score_mcse", "mean"),
            calib=("calibration_error_mean", "mean"),
            calib_mcse=("calibration_error_mcse", "mean"),
        )
        .reset_index()
    )

    body = [
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Recovery of the true survival function beside the "
        r"conventional metrics, averaged over the design. Monte Carlo standard "
        r"errors in parentheses.}",
        r"\label{tab:main}",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Mechanism & Estimator & MISE & C-index & IBS & Calibration \\",
        r"\midrule",
    ]
    for dgp, block in grouped.groupby("dgp"):
        for position, row in enumerate(block.itertuples()):
            label = f"\\texttt{{{_escape(dgp)}}}" if position == 0 else ""
            body.append(
                f"{label} & \\texttt{{{_escape(row.estimator_id)}}} & "
                f"{_pm(row.mise, row.mise_mcse, 5)} & "
                f"{_pm(row.c_index, row.c_index_mcse, 3)} & "
                f"{_pm(row.ibs, row.ibs_mcse, 3)} & "
                f"{_pm(row.calib, row.calib_mcse, 3)} \\\\"
            )
        body.append(r"\midrule")
    body[-1] = r"\bottomrule"
    body += [r"\end{tabular}", r"\end{table}", ""]
    _write(
        out / "table3_main_results.tex",
        "\n".join(body),
        "results/processed/summary.parquet",
    )


def table_parameter_recovery(summary: pd.DataFrame, out: Path) -> None:
    """Only where a fitted coefficient estimates a generating parameter.

    The table is short by design. Its point is that an unbiased coefficient and
    a recovered survival function are different achievements.
    """
    if "beta_bias_scalar_mean" not in summary.columns:
        print("  table4: skipped, no parameter-recovery columns")
        return

    applicable = summary.dropna(subset=["beta_bias_scalar_mean"])
    if applicable.empty:
        print("  table4: skipped, no cell had a corresponding parameter")
        return

    body = [
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Parameter recovery, for the mechanism-estimator pairs where "
        r"a fitted coefficient estimates a generating parameter. Reported "
        r"nowhere else: elsewhere the estimands differ and a difference would "
        r"not be a bias.}",
        r"\label{tab:recovery}",
        r"\begin{tabular}{llrr}",
        r"\toprule",
        r"Mechanism & Estimator & Bias of $\hat\beta$ & MISE \\",
        r"\midrule",
    ]
    for row in applicable.itertuples():
        body.append(
            f"\\texttt{{{_escape(str(row.dgp))}}} & "
            f"\\texttt{{{_escape(str(row.estimator_id))}}} & "
            f"{_pm(row.beta_bias_scalar_mean, getattr(row, 'beta_bias_scalar_mcse', float('nan')), 4)} & "
            f"{_pm(row.mise_mean, row.mise_mcse, 5)} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    _write(
        out / "table4_parameter_recovery.tex",
        "\n".join(body),
        "results/processed/summary.parquet",
    )


def table_failures(failures: pd.DataFrame, out: Path) -> None:
    """Failure is performance, so it gets a table rather than a footnote."""
    if failures.empty or "fit_failure_rate" not in failures.columns:
        print("  table5: skipped, no failure table")
        return

    grouped = (
        failures.groupby("estimator_id")
        .agg(
            attempted=("attempted", "sum"),
            fit_failures=("fit_failures", "sum"),
            score_failures=("score_failures", "sum"),
        )
        .reset_index()
    )
    grouped["rate"] = grouped["fit_failures"] / grouped["attempted"]
    # The rate is a proportion estimated from a finite number of attempts, so
    # it carries a standard error like any other estimate here. A failure rate
    # of 0 out of 20 and 0 out of 2000 are not the same claim.
    grouped["rate_se"] = (
        grouped["rate"] * (1.0 - grouped["rate"]) / grouped["attempted"]
    ) ** 0.5

    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Fit and scoring failures. Replications where an estimator "
        r"failed contribute no metrics but are counted here, so a fragile "
        r"estimator is not flattered by the cells it could not fit.}",
        r"\label{tab:failures}",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Estimator & Attempted & Fit failures & Scoring failures & Rate \\",
        r"\midrule",
    ]
    for row in grouped.itertuples():
        body.append(
            f"\\texttt{{{_escape(str(row.estimator_id))}}} & {int(row.attempted)} & "
            f"{int(row.fit_failures)} & {int(row.score_failures)} & "
            f"{_pm(row.rate, row.rate_se, 4)} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    _write(
        out / "table5_failures.tex",
        "\n".join(body),
        "results/processed/failures.parquet",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=str(HERE.parent / "config"))
    parser.add_argument(
        "--processed", default=str(HERE.parent / "results" / "processed")
    )
    parser.add_argument("--out", default=str(HERE.parent / "paper" / "tables"))
    arguments = parser.parse_args()

    out = Path(arguments.out)
    processed = Path(arguments.processed)

    study = load_study(arguments.config)
    print("design tables:")
    table_scenarios(study, out)
    table_estimators(study, out)

    summary_path = processed / "summary.parquet"
    if not summary_path.exists():
        print(f"\nno results at {summary_path}; tables 3-5 skipped")
        return 0

    summary = pd.read_parquet(summary_path)
    failures = (
        pd.read_parquet(processed / "failures.parquet")
        if (processed / "failures.parquet").exists()
        else pd.DataFrame()
    )

    print("result tables:")
    table_main_results(summary, out)
    table_parameter_recovery(summary, out)
    table_failures(failures, out)

    print(f"\nwritten to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
