"""Generate every numerical table in the paper from saved result files.

    python scripts/make_tables.py --processed results/processed --config config

Writes LaTeX to ``paper/tables/``. **No numeric value is ever typed into the
manuscript by hand.** Each file carries a generated-by header, and
``tests/test_tables.py`` fails if a table in ``paper/tables/`` lacks one --
which is what stops a number being pasted in and then quietly diverging from
the results it came from.

Tables 1 and 2 describe the design and can be produced before any run. Tables
3 to 5 need results and are skipped with a message when they are absent, rather
than emitting an empty table that looks finished.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))

from survival_misspec.config import load_study  # noqa: E402

HEADER = (
    "% Generated by scripts/make_tables.py from {source}.\n"
    "% Do not edit: re-run the script. A hand-edited number here would no\n"
    "% longer correspond to any result and nothing would detect the drift.\n"
)


def _escape(text: str) -> str:
    for old, new in (("_", r"\_"), ("%", r"\%"), ("&", r"\&")):
        text = text.replace(old, new)
    return text


def _write(path: Path, body: str, source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER.format(source=source) + body, encoding="utf-8")
    print(f"  {path.name}")


def _pm(mean: float, mcse: float, digits: int = 4) -> str:
    """A value with its Monte Carlo error, never one without the other."""
    if pd.isna(mean):
        return "---"
    if pd.isna(mcse):
        return f"{mean:.{digits}f}"
    return f"{mean:.{digits}f} \\;({mcse:.{digits}f})"


def _mean_and_mcse(
    frame: pd.DataFrame, mean_column: str, mcse_column: str
) -> pd.Series:
    """Mean of scenario means, with independent cell MCSEs propagated."""
    values = pd.to_numeric(frame[mean_column], errors="coerce")
    standard_errors = pd.to_numeric(frame[mcse_column], errors="coerce")
    keep = values.notna()
    if not keep.any():
        return pd.Series({"mean": float("nan"), "mcse": float("nan")})

    values = values[keep]
    standard_errors = standard_errors[keep].fillna(0.0)
    mean = float(values.mean())
    mcse = float(math.sqrt(float((standard_errors**2).sum())) / len(values))
    return pd.Series({"mean": mean, "mcse": mcse})


def _wilson_interval(
    failures: int, attempted: int, z: float = 1.96
) -> tuple[float, float]:
    """Wilson score interval for a binomial failure probability."""
    if attempted <= 0:
        return float("nan"), float("nan")
    p = failures / attempted
    denominator = 1.0 + z**2 / attempted
    centre = (p + z**2 / (2 * attempted)) / denominator
    radius = z * math.sqrt((p * (1 - p) + z**2 / (4 * attempted)) / attempted)
    radius /= denominator
    return max(0.0, centre - radius), min(1.0, centre + radius)


def table_scenarios(study, out: Path) -> None:
    rows = []
    seen = set()
    for scenario in study.scenarios:
        if scenario.dgp in seen:
            continue
        seen.add(scenario.dgp)
        rows.append((scenario.dgp, scenario.misspecification))

    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Data-generating mechanisms, and what each does to a "
        r"proportional-hazards model.}",
        r"\label{tab:scenarios}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"Mechanism & Departure from proportional hazards \\",
        r"\midrule",
    ]
    for dgp, misspecification in sorted(rows):
        body.append(f"\\texttt{{{_escape(dgp)}}} & {_escape(misspecification)} \\\\")
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    _write(out / "table1_scenarios.tex", "\n".join(body), "config/simulation.yaml")


def table_estimators(study, out: Path) -> None:
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Estimators and the assumptions each makes.}",
        r"\label{tab:estimators}",
        r"\begin{tabular}{lp{9cm}}",
        r"\toprule",
        r"Estimator & Assumptions \\",
        r"\midrule",
    ]
    for estimator in study.estimators:
        body.append(
            f"\\texttt{{{_escape(estimator.estimator_id)}}} & "
            f"{_escape(estimator.assumptions)} \\\\"
        )
    body += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    _write(out / "table2_estimators.tex", "\n".join(body), "config/estimators.yaml")


def table_main_results(summary: pd.DataFrame, out: Path) -> None:
    """The primary loss beside the metrics that are supposed to stand in for it.

    Every entry carries its Monte Carlo error. Two values whose intervals
    overlap are not distinguishable at this replication count, and the table is
    laid out so a reader can see that rather than having to be told.
    """
    needed = [
        "dgp",
        "estimator_id",
        "root_mean_integrated_squared_error_mean",
        "root_mean_integrated_squared_error_mcse",
    ]
    missing = [c for c in needed if c not in summary.columns]
    if missing:
        print(f"  table3: skipped, missing {missing}")
        return

    rows = []
    for (dgp, estimator_id), block in summary.groupby(["dgp", "estimator_id"]):
        record = {"dgp": dgp, "estimator_id": estimator_id}
        for label, mean_column, mcse_column in (
            (
                "rmise",
                "root_mean_integrated_squared_error_mean",
                "root_mean_integrated_squared_error_mcse",
            ),
            ("c_index", "c_index_harrell_mean", "c_index_harrell_mcse"),
            ("ibs", "integrated_brier_score_mean", "integrated_brier_score_mcse"),
            ("calib", "calibration_error_mean", "calibration_error_mcse"),
        ):
            estimate = _mean_and_mcse(block, mean_column, mcse_column)
            record[label] = estimate["mean"]
            record[f"{label}_mcse"] = estimate["mcse"]
        rows.append(record)
    grouped = pd.DataFrame.from_records(rows)

    body = [
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Recovery of the true survival function beside the "
        r"conventional metrics, averaged over the design. Monte Carlo standard "
        r"errors in parentheses.}",
        r"\label{tab:main}",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Mechanism & Estimator & RMISE & C-index & IBS & Calibration \\",
        r"\midrule",
    ]
    for dgp, block in grouped.groupby("dgp"):
        for position, row in enumerate(block.itertuples()):
            label = f"\\texttt{{{_escape(dgp)}}}" if position == 0 else ""
            body.append(
                f"{label} & \\texttt{{{_escape(row.estimator_id)}}} & "
                f"{_pm(row.rmise, row.rmise_mcse, 4)} & "
                f"{_pm(row.c_index, row.c_index_mcse, 3)} & "
                f"{_pm(row.ibs, row.ibs_mcse, 3)} & "
                f"{_pm(row.calib, row.calib_mcse, 3)} \\\\"
            )
        body.append(r"\midrule")
    body[-1] = r"\bottomrule"
    body += [r"\end{tabular}", r"\end{table}", ""]
    _write(
        out / "table3_main_results.tex",
        "\n".join(body),
        "results/processed/summary.parquet",
    )


def table_parameter_recovery(summary: pd.DataFrame, out: Path) -> None:
    """Only where a fitted coefficient estimates a generating parameter.

    The table is short by design. Its point is that an unbiased coefficient and
    a recovered survival function are different achievements.
    """
    if "beta_abs_bias_mean_mean" not in summary.columns:
        print("  table4: skipped, no parameter-recovery columns")
        return

    applicable = summary.dropna(subset=["beta_abs_bias_mean_mean"])
    if applicable.empty:
        print("  table4: skipped, no cell had a corresponding parameter")
        return

    body = [
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Parameter recovery, for the mechanism-estimator pairs where "
        r"a fitted coefficient estimates a generating parameter. Reported "
        r"nowhere else: elsewhere the estimands differ and a difference would "
        r"not be a bias.}",
        r"\label{tab:recovery}",
        r"\begin{tabular}{llrrr}",
        r"\toprule",
        r"Mechanism & Estimator & Mean bias & Mean absolute bias & RMISE \\",
        r"\midrule",
    ]
    for row in applicable.itertuples():
        signed = (
            row.beta_bias_scalar_mean
            if hasattr(row, "beta_bias_scalar_mean")
            and not pd.isna(row.beta_bias_scalar_mean)
            else row.beta_bias_mean_mean
        )
        signed_mcse = (
            row.beta_bias_scalar_mcse
            if hasattr(row, "beta_bias_scalar_mcse")
            and not pd.isna(row.beta_bias_scalar_mcse)
            else row.beta_bias_mean_mcse
        )
        rmise = _pm(
            row.root_mean_integrated_squared_error_mean,
            row.root_mean_integrated_squared_error_mcse,
            4,
        )
        body.append(
            f"\\texttt{{{_escape(str(row.dgp))}}} & "
            f"\\texttt{{{_escape(str(row.estimator_id))}}} & "
            f"{_pm(signed, signed_mcse, 4)} & "
            f"{_pm(row.beta_abs_bias_mean_mean, row.beta_abs_bias_mean_mcse, 4)} & "
            f"{rmise} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    _write(
        out / "table4_parameter_recovery.tex",
        "\n".join(body),
        "results/processed/summary.parquet",
    )


def table_failures(failures: pd.DataFrame, out: Path) -> None:
    """Failure is performance, so it gets a table rather than a footnote."""
    if failures.empty or "fit_failure_rate" not in failures.columns:
        print("  table5: skipped, no failure table")
        return

    grouped = (
        failures.groupby("estimator_id")
        .agg(
            attempted=("attempted", "sum"),
            fit_failures=("fit_failures", "sum"),
            score_failures=("score_failures", "sum"),
        )
        .reset_index()
    )
    grouped["rate"] = grouped["fit_failures"] / grouped["attempted"]
    intervals = [
        _wilson_interval(int(row.fit_failures), int(row.attempted))
        for row in grouped.itertuples()
    ]
    grouped["rate_low"] = [low for low, _ in intervals]
    grouped["rate_high"] = [high for _, high in intervals]

    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Fit and scoring failures. Replications where an estimator "
        r"failed contribute no metrics but are counted here, so a fragile "
        r"estimator is not flattered by the cells it could not fit.}",
        r"\label{tab:failures}",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Estimator & Attempted & Fit failures & Scoring failures & Rate (95\% CI) \\",
        r"\midrule",
    ]
    for row in grouped.itertuples():
        body.append(
            f"\\texttt{{{_escape(str(row.estimator_id))}}} & {int(row.attempted)} & "
            f"{int(row.fit_failures)} & {int(row.score_failures)} & "
            f"{row.rate:.4f} [{row.rate_low:.4f}, {row.rate_high:.4f}] \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    _write(
        out / "table5_failures.tex",
        "\n".join(body),
        "results/processed/failures.parquet",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=str(HERE.parent / "config"))
    parser.add_argument(
        "--processed", default=str(HERE.parent / "results" / "processed")
    )
    parser.add_argument("--out", default=str(HERE.parent / "paper" / "tables"))
    arguments = parser.parse_args()

    out = Path(arguments.out)
    processed = Path(arguments.processed)

    study = load_study(arguments.config)
    print("design tables:")
    table_scenarios(study, out)
    table_estimators(study, out)

    summary_path = processed / "summary.parquet"
    if not summary_path.exists():
        print(f"\nno results at {summary_path}; tables 3-5 skipped")
        return 0

    summary = pd.read_parquet(summary_path)
    failures = (
        pd.read_parquet(processed / "failures.parquet")
        if (processed / "failures.parquet").exists()
        else pd.DataFrame()
    )

    print("result tables:")
    table_main_results(summary, out)
    table_parameter_recovery(summary, out)
    table_failures(failures, out)

    print(f"\nwritten to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
