from gen_surv.censoring import rexpocens as rexpocens, runifcens as runifcens
from gen_surv.validate import validate_gen_thmm_inputs as validate_gen_thmm_inputs

def calculate_transitions(z1: float, cens_par: float, beta: list, rate: list, rfunc) -> dict: ...
def gen_thmm(n, model_cens, cens_par, beta, covar, rate): ...
