def validate_gen_cphm_inputs(n: int, model_cens: str, cens_par: float, covar: float): ...
def validate_gen_cmm_inputs(n: int, model_cens: str, cens_par: float, beta: list, covar: float, rate: list): ...
def validate_gen_tdcm_inputs(n: int, dist: str, corr: float, dist_par: list, model_cens: str, cens_par: float, beta: list, lam: float): ...
def validate_gen_thmm_inputs(n: int, model_cens: str, cens_par: float, beta: list, covar: float, rate: list): ...
def validate_dg_biv_inputs(n: int, dist: str, corr: float, dist_par: list): ...
def validate_gen_aft_log_normal_inputs(n, beta, sigma, model_cens, cens_par) -> None: ...
