"""No number in the manuscript may be typed by hand.

The protocol requires that every value in the paper be reconstructible from a
result file. That is unenforceable by convention -- somebody pastes a number
into a table during a revision, the experiment is re-run, and the paper now
contains a figure that corresponds to nothing. Nothing would detect it.

So every table under ``paper/tables/`` must carry the header
``scripts/make_tables.py`` writes, and the manuscript itself must not contain
free-standing numeric values outside the places where they are structural.
"""

from __future__ import annotations

import pathlib
import re

import pytest

PAPER = pathlib.Path(__file__).resolve().parent.parent / "paper"
GENERATED_MARKER = "Generated by scripts/make_tables.py"


def _tables() -> list[pathlib.Path]:
    directory = PAPER / "tables"
    if not directory.exists():
        return []
    return sorted(directory.glob("*.tex"))


def test_every_table_is_generated() -> None:
    """A table without the header was written by a person, which is the problem."""
    tables = _tables()
    if not tables:
        pytest.skip("no tables generated yet")

    handwritten = [
        path.name
        for path in tables
        if GENERATED_MARKER not in path.read_text(encoding="utf-8")
    ]

    assert not handwritten, (
        "These tables do not carry the generated-by header, so their numbers "
        "cannot be traced to a result file:\n  " + "\n  ".join(handwritten) + "\n\n"
        "Regenerate with `python scripts/make_tables.py` rather than editing "
        "the LaTeX."
    )


def test_generated_tables_report_monte_carlo_error() -> None:
    """A mean without its uncertainty invites a comparison that is not there.

    Tables 1 and 2 describe the design and carry no estimates, so they are
    exempt. Any table reporting a Monte Carlo average must show its error.
    """
    for path in _tables():
        text = path.read_text(encoding="utf-8")
        if "table1" in path.name or "table2" in path.name:
            continue
        if "---" in text and text.count("\\\\") < 3:
            continue  # a table with no data rows yet
        assert (
            "\\;(" in text or "---" in text
        ), f"{path.name} reports values without Monte Carlo standard errors"


def test_manuscript_sections_contain_no_typed_results() -> None:
    """Section files hold structure and prose, never numeric results.

    Numbers appearing in prose must be \\input from a generated macro file.
    This catches the common failure: a value quoted in the text during drafting
    that then drifts from the table beside it.

    Comments are exempt -- the skeleton records pilot values as design evidence,
    clearly marked -- and so are section numbering and citation years.
    """
    sections = PAPER / "sections"
    if not sections.exists():
        pytest.skip("no sections yet")

    # A decimal with three or more places is a result, not a year or a count.
    result_like = re.compile(r"\d+\.\d{3,}")

    offenders: list[str] = []
    for path in sorted(sections.glob("*.tex")):
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("%") or not stripped:
                continue
            if result_like.search(stripped):
                offenders.append(f"{path.name}:{number}: {stripped[:80]}")

    assert not offenders, (
        "Numeric results appear directly in the manuscript text. They must be "
        "\\input from a generated file instead:\n  " + "\n  ".join(offenders)
    )


def test_main_tex_declares_the_draft_state() -> None:
    """While the experiment is unfrozen the paper must say so on its face.

    A draft that reads like a finished paper is the one that gets circulated by
    accident.
    """
    main = PAPER / "main.tex"
    if not main.exists():
        pytest.skip("no manuscript yet")

    text = main.read_text(encoding="utf-8")
    lock = PAPER.parent / "protocol" / "experiment_lock.json"

    if not lock.exists():
        assert "draftbanner" in text, (
            "no experiment lock exists, so the manuscript must carry the draft "
            "banner declaring that there are no production results"
        )
