# .github/workflows/bump-version.yml
name: Sync Version on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Synchronize tag and pyproject version
        run: python scripts/check_version_match.py --fix --write

