name: Documentation Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-3.11-${{ hashFiles('**/poetry.lock') }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --with docs
      - name: Build documentation
        run: poetry run sphinx-build -W -b html docs/source docs/build
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: documentation
          path: docs/build/
